export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_TOPLEVEL_CATEGORIES = 'GET_TOPLEVEL_CATEGORIES';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const SET_FITBIT_ACCESS_TOKEN = 'SET_FITBIT_ACCESS_TOKEN';
export const GET_FITBIT_DAILY_ACTIVITY_SUMMARY = 'GET_FITBIT_DAILY_ACTIVITY_SUMMARY';
export const GET_FITBIT_YESTERDAY_ACTIVITY_SUMMARY = 'GET_YESTERDAY_DAILY_ACTIVITY_SUMMARY';
export const LOGOUT = 'LOGOUT';

