export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const SET_FITBIT_ACCESS_TOKEN = 'SET_FITBIT_ACCESS_TOKEN';
export const GET_FITBIT_DAILY_ACTIVITY_SUMMARY = 'GET_FITBIT_DAILY_ACTIVITY_SUMMARY';
export const GET_FITBIT_DAILY_HEARTRATE_SUMMARY = 'GET_FITBIT_DAILY_HEARTRATE_SUMMARY';
export const LOGOUT = 'LOGOUT';

